# Dependencies
markdown: redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tao Wu
tagline:          'Tao&#39s Homepage'
description:      'wu577(at)purdue(dot)edu'
url:              http://hyde.getpoole.com
baseurl:          https://www.cs.purdue.edu/homes/wu577/

author:
  name:           'Tao Wu'
  url:            https://www.cs.purdue.edu/homes/wu577/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"