# Dependencies
markdown: redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tao Wu
tagline:          'Tao&#39s Homepage'
#description:      'Ph.D. Candidate<br><a href="https://www.cs.purdue.edu" target="_blank">Computer Science</a><br><a href="http://www.purdue.edu" target="_blank">Purdue University</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"